name: server_learning
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  dart_jsonwebtoken: ^2.14.0
  mysql1: ^0.20.0
  pool: ^1.5.1
  redis: ^4.0.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  web_socket_channel: ^2.4.0
  yaml: ^3.1.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
